spring:
  application:
    name: cmc15th_hackathon
  datasource:
    url: jdbc:mysql://hackathon.cdggye4yurim.ap-northeast-2.rds.amazonaws.com
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Zedtex-9xopmi-zejmup
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

